//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organaizer_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerPass
    {
        public int IdManagerPass { get; set; }
        public Nullable<int> Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string SocialNetwork { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
